"""SPLIT-native obs allow-list for ``proseg_purified.h5ad``.

The user (internal issue review) requires that
``proseg_purified.h5ad`` carry ONLY the metadata that SPLIT itself
produces — no leakage of proseg_raw-side columns such as
``total_counts``. The offending leak came from
``r/_preserve_meta.R`` copying every non-Seurat, non-RCTD column of
``xe_unpurified@meta.data`` onto the purified Seurat before it was
exported to mtx/h5ad.

Since the caller will not re-run SPLIT, the fix is applied on the h5ad side:

    * ``stages/mtx_to_h5ad`` calls :func:`filter_purified_obs` after
      building the purified AnnData, so freshly-emitted h5ads never
      carry the foreign columns.

    * The ``strip-purified-obs`` CLI subcommand (see
      ``rctd_split.cli``) invokes the same filter on an existing
      ``proseg_purified.h5ad`` in place, with a timestamped ``.bak``
      copy so the pre-strip file is recoverable.

Both paths use the exact same allow-list defined here.

Allow-list membership rationale:

    * Seurat-managed (``orig.ident``, ``nCount_<assay>``,
      ``nFeature_<assay>``) — computed by CreateSeuratObject against
      the *purified* counts; these are the numerically correct
      purified-side per-cell totals (the request explicitly named
      ``nCount_Proseg`` as the purified counts column).

    * RCTD / SPLIT results (``first_type``, ``second_type``,
      ``spot_class``, ``purification_status``, ``w1_larger_w2``,
      ``same_class``) — emitted by ``SPLIT::run_post_process_RCTD``
      (attached to unpurified) and threaded through
      ``SPLIT::purify(...)$cell_meta`` onto the purified Seurat.

    * Post-SPLIT pipeline additions (``n_counts``, ``leiden_*``) —
      generated by the ``postprocess`` stage on the h5ad-side (``n_counts``
      is a side-effect of ``sc.pp.filter_cells(min_counts=...)``;
      ``leiden_<resolution>`` is written by the leiden step). The QC
      report needs both; they are NOT SPLIT output but they ARE
      canonical downstream metadata that must survive the strip.

    * Spatial centroid columns (``centroid_x``, ``centroid_y``) —
      required inputs to ``celltype_writeback`` (Stage 8), which reads
      ``purified.obs[reference_x_col]`` / ``[reference_y_col]`` to map
      RCTD celltype labels onto ``xenium_ranger.h5ad`` via nearest
      neighbor. These originate from xenium-preprocess's xenium-preprocess
      enrichments and travel to purified via
      ``preserve_meta_from_unpurified`` — strictly speaking they are
      NOT SPLIT output, but the Stage-D pipeline depends on them being
      on purified.obs at the point celltype_writeback runs. Kept on
      the allow-list; the user's retroactive strip after Stage 8 has
      already completed can be more aggressive if she needs.
"""
from __future__ import annotations


# Exact-name allow-list. Anything in this set stays on purified.obs.
_ALLOWED_EXACT: frozenset[str] = frozenset({
    # Seurat-managed identity column.
    "orig.ident",
    # SPLIT / RCTD result columns emitted by
    # SPLIT::run_post_process_RCTD + SPLIT::purify's cell_meta.
    "first_type",
    "second_type",
    "spot_class",
    "purification_status",
    "w1_larger_w2",
    "same_class",
    # Post-SPLIT pipeline addition (sc.pp.filter_cells side-effect).
    "n_counts",
    # Spatial centroids — celltype_writeback (Stage 8) reads these off
    # purified.obs. Preserved through the strip so a fresh pipeline
    # run does not fail at Stage 8.
    "centroid_x",
    "centroid_y",
})


# Prefix allow-list. Anything whose name starts with one of these
# stays on purified.obs. Prefixes let us cover the parametric shape
# of Seurat's per-assay columns (``nCount_<assay>`` /
# ``nFeature_<assay>``) and the postprocess-added
# ``leiden_<resolution>`` without having to know the assay name /
# resolution values at this layer.
_ALLOWED_PREFIXES: tuple[str, ...] = (
    "nCount_",
    "nFeature_",
    "leiden_",
)


def is_split_native_obs_col(col: str) -> bool:
    """Return True iff ``col`` is on the SPLIT-native purified.obs allow-list."""
    if col in _ALLOWED_EXACT:
        return True
    return any(col.startswith(prefix) for prefix in _ALLOWED_PREFIXES)


def filter_purified_obs(adata) -> list[str]:
    """Drop non-SPLIT-native columns from ``adata.obs`` in place.

    Returns the sorted list of column names that were dropped so the
    caller can log them.
    """
    to_drop = sorted(
        c for c in adata.obs.columns if not is_split_native_obs_col(c)
    )
    if to_drop:
        adata.obs = adata.obs.drop(columns=to_drop)
    return to_drop
