#!/usr/bin/env bash
# scripts/write-env-config.sh — the final step of installation: records
# RESOLVED ABSOLUTE values into the gitignored scripts/env.local.conf,
# so every sbatch job reads a fixed, already-resolved config instead of
# re-deriving `$HOME`-relative paths inside its own (possibly different)
# environment instance. See scripts/lib/env_config.sh for the consumer
# side and the full rationale.
#
# Usage:
#   scripts/write-env-config.sh \
#       --env-prefix   /abs/path/to/micromamba/envs/xenium \
#       --r-lib-dir    /abs/path/to/R/library \
#       [--r-module    fhR/4.4.1-foss-2023b] \
#       [--micromamba-bin /abs/path/to/micromamba]
#
# --env-prefix and --r-lib-dir must already exist (this script records,
# it does not create, the environment — run the install steps in
# docs/installation.md first). --r-module defaults to the module this
# pipeline has always assumed; --micromamba-bin auto-detects via
# `command -v micromamba` if not passed.

set -euo pipefail

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
OUT="$SCRIPT_DIR/env.local.conf"

ENV_PREFIX=""
R_LIB_DIR=""
R_MODULE="fhR/4.4.1-foss-2023b"
MICROMAMBA_BIN=""

while [[ $# -gt 0 ]]; do
    case "$1" in
        --env-prefix)      ENV_PREFIX="$2"; shift 2 ;;
        --r-lib-dir)       R_LIB_DIR="$2"; shift 2 ;;
        --r-module)        R_MODULE="$2"; shift 2 ;;
        --micromamba-bin)  MICROMAMBA_BIN="$2"; shift 2 ;;
        -h|--help)
            sed -n '2,20p' "$0"; exit 0 ;;
        *)
            echo "error: unknown argument: $1" >&2; exit 2 ;;
    esac
done

: "${ENV_PREFIX:?--env-prefix is required (absolute path to the micromamba env PREFIX)}"
: "${R_LIB_DIR:?--r-lib-dir is required (absolute path to the R library holding spacexr/SPLIT)}"

if [[ ! -d "$ENV_PREFIX" ]]; then
    echo "error: --env-prefix does not exist: $ENV_PREFIX" >&2
    echo "       Create it first (scripts/create-env.sh -p \"$ENV_PREFIX\" -f environments/xenium.yml)." >&2
    exit 3
fi
ENV_PREFIX=$(cd "$ENV_PREFIX" && pwd)   # canonicalize to an absolute path

if [[ ! -d "$R_LIB_DIR" ]]; then
    echo "error: --r-lib-dir does not exist: $R_LIB_DIR" >&2
    echo "       Create it and install spacexr/SPLIT/Seurat into it first (docs/installation.md § R side)." >&2
    exit 3
fi
R_LIB_DIR=$(cd "$R_LIB_DIR" && pwd)

if [[ -z "$MICROMAMBA_BIN" ]]; then
    if ! MICROMAMBA_BIN=$(command -v micromamba); then
        echo "error: micromamba not found on PATH and --micromamba-bin not given." >&2
        exit 4
    fi
fi
if [[ ! -x "$MICROMAMBA_BIN" ]]; then
    echo "error: --micromamba-bin is not executable: $MICROMAMBA_BIN" >&2
    exit 4
fi
# Canonicalize (command -v can return a relative-looking path on some shells).
MICROMAMBA_BIN=$(cd "$(dirname "$MICROMAMBA_BIN")" && pwd)/$(basename "$MICROMAMBA_BIN")

cat > "$OUT" <<EOF
# Generated by scripts/write-env-config.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ).
# Machine-local, gitignored — resolved ABSOLUTE values for THIS install.
# Do not hand-edit; re-run scripts/write-env-config.sh instead.
MICROMAMBA_BIN=$MICROMAMBA_BIN
XENIUM_ENV_PREFIX=$ENV_PREFIX
R_LIB_DIR=$R_LIB_DIR
R_MODULE=$R_MODULE
EOF

echo "[write-env-config] wrote $OUT:"
sed 's/^/[write-env-config]   /' "$OUT"
echo "[write-env-config] verify with: scripts/env-preflight.sh"
